name: cd-shifumi

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v3

    - name: move files to dist/
      run: |
        mkdir dist
        cp index.html style.css app.js dist/

    - name: Execute SSH commands to reset folder
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          mv /var/www/shifumi/public/dist/* /var/www/shifumi/public/
          # Remove the empty dist folder
          sudo rm -rf /var/www/shifumi/*

    - name: Deploy via SFTP
      uses: appleboy/scp-action@v0.1.5
      with:
        debug: true
        host: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        source: "dist/**"
        strip_components: 1
        target: "/var/www/shifumi/public"
